# Generated by Django 5.2.3 on 2025-06-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_achievement_achievementcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='achievement',
            field=models.ManyToManyField(through='cats.AchievementCat', to='cats.achievement'),
        ),
    ]
